# Generated by Django 5.2.12 on 2026-03-05 09:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_id', models.CharField(max_length=100, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.TextField(null=True)),
                ('category', models.CharField(max_length=255, null=True)),
                ('rating', models.FloatField(null=True)),
                ('total_reviews', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('review_id', models.CharField(max_length=255, unique=True)),
                ('reviewer_name', models.CharField(max_length=255)),
                ('rating', models.IntegerField()),
                ('text', models.TextField()),
                ('response', models.TextField(blank=True, null=True)),
                ('review_link', models.URLField()),
                ('review_date', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='Home.business')),
            ],
        ),
    ]
